NODE_ENV=development \
PAGE_SIZE=3 \
DASHBOARD_SERVER="http://localhost:8001" \
PORT=8001 \
STORAGE_PATH=/tmp/test-data \
REQUIRE_PROFILE_EMAIL=true \
REQUIRE_PROFILE_NAME=true \
ID_LENGTH=8 \
node main.js
