name: mocha-postgresql

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432/tcp
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
 
    - name: Setup dependencies
      run: |
        npm install mocha -g &&
        npm install puppeteer @userdashboard/storage-postgresql --no-save
    - name: Test
      run: |
        npm test || exit 1
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9007"
        DOMAIN: "localhost"
        PORT: 9007
        STORAGE_ENGINE: "@userdashboard/storage-postgresql"
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
        DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres"
        DEBUG_ERRORS: true
        PG_HOSTNAME: postgres
        PG_PASSWORD: postgres
        PG_DB: postgres
        PG_PORT: 5432
        ENCRYPTION_SECRET: "12345678901234567890123456789012"
        ENCRYPTION_SECRET_IV: "1234123412341234"
