name: mocha-postgresql

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    services:
        postgres:
          image: postgres:10.8
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
          ports:
          - 5432:5432
          # needed because the postgres container does not provide a healthcheck
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
 
    - name: Setup dependencies
      run: |
        npm install mocha -g &&
        npm install puppeteer @userdashboard/storage-postgresql --no-save
    - name: Test
      run: |
        npm test || exit 1
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9007"
        DOMAIN: "localhost"
        PORT: 9007
        STORAGE_ENGINE: "@userdashboard/storage-postgresql"
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
        DATABASE_URL: "postgres://postgres:postgres@postgres:5432/daspostgreshboard"
        DEBUG_ERRORS: true
