name: mocha-encrypted-s3

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    services: localstack/localstack:latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup dependencies
      run: |
        npm install mocha puppeteer @userdashboard/storage-s3 --no-save
    - name: Test
      run: |
        node --max_old_space_size=8192 ./node_modules/mocha/bin/mocha src --recursive --no-colors --timeout 120000 --slow 120000 || exit 1
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9007"
        DOMAIN: "localhost"
        PORT: 9007
        STORAGE_ENGINE: @userdashboard/storage-s3
        S3_BUCKET_NAME: the_name 
        S3_ENDPOINT: localhost:5000
        ACCESS_KEY_ID: secret from amazon 
        SECRET_ACCESS_KEY: secret from amazon
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
        DEBUG_ERRORS: true