name: mocha-fs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup dependencies
      run: |
        npm install mocha -g &&
        npm install puppeteer --no-save
    - name: Test internal API
      run: |
        npm test  -- --fgrep "internal-api" || exit 1
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        PORT: 9000
        STORAGE_PATH: /tmp/test-data
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
    - name: Test server handlers
      run: |
        npm test  -- --fgrep "server" || exit 1
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9001"
        DOMAIN: "localhost"
        PORT: 9001
        STORAGE_PATH: /tmp/test-data
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
        ENCRYPTION_SECRET: "12345678901234567890123456789012"
        ENCRYPTION_SECRET_IV: "1234123412341234"
    - name: Test content handlers
      run: |
        npm test -- --fgrep "content" || exit 1
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9002"
        DOMAIN: "localhost"
        PORT: 9002
        STORAGE_PATH: /tmp/test-data
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
    - name: Test user API
      run: |
        npm test -- --fgrep "api/user" || exit 1
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9003"
        DOMAIN: "localhost"
        PORT: 9003
        STORAGE_PATH: /tmp/test-data1
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
    - name: Test administrator API
      run: |
        npm test -- --fgrep "api/administrator" || exit 1
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9004"
        DOMAIN: "localhost"
        PORT: 9004
        STORAGE_PATH: /tmp/test-data2
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
    - name: Test user UI
      run: |
        npm test -- --fgrep "www/account" || exit 1
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9005"
        DOMAIN: "localhost"
        PORT: 9005
        STORAGE_PATH: /tmp/test-data3
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
    - name: Test administrator UI
      run: |
        npm test -- --fgrep "www/administrator" || exit 1
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9006"
        DOMAIN: "localhost"
        PORT: 9006
        STORAGE_PATH: /tmp/test-data4
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
    - name: Test internal API (encryption)
      run: |
        npm test  -- --fgrep "internal-api" || exit 1
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9007"
        DOMAIN: "localhost"
        PORT: 9007
        STORAGE_PATH: /tmp/test-data
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
        ENCRYPTION_SECRET: "12345678901234567890123456789012"
        ENCRYPTION_SECRET_IV: "1234123412341234"
    - name: Test server handlers (encryption)
      run: |
        npm test  -- --fgrep "server" || exit 1
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9008"
        DOMAIN: "localhost"
        PORT: 9008
        STORAGE_PATH: /tmp/test-data
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
        ENCRYPTION_SECRET: "12345678901234567890123456789012"
        ENCRYPTION_SECRET_IV: "1234123412341234"
    - name: Test content handlers (encryption)
      run: |
        npm test -- --fgrep "content" || exit 1
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9009"
        DOMAIN: "localhost"
        PORT: 9009
        STORAGE_PATH: /tmp/test-data
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
        ENCRYPTION_SECRET: "12345678901234567890123456789012"
        ENCRYPTION_SECRET_IV: "1234123412341234"
    - name: Test user API (encryption)
      run: |
        npm test -- --fgrep "api/user" || exit 1
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9010"
        DOMAIN: "localhost"
        PORT: 9010
        STORAGE_PATH: /tmp/test-data1
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
        ENCRYPTION_SECRET: "12345678901234567890123456789012"
        ENCRYPTION_SECRET_IV: "1234123412341234"
    - name: Test administrator API (encryption)
      run: |
        npm test -- --fgrep "api/administrator" || exit 1
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9011"
        DOMAIN: "localhost"
        PORT: 9011
        STORAGE_PATH: /tmp/test-data2
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
        ENCRYPTION_SECRET: "12345678901234567890123456789012"
        ENCRYPTION_SECRET_IV: "1234123412341234"
    - name: Test user UI (encryption)
      run: |
        npm test -- --fgrep "www/account" || exit 1
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9012"
        DOMAIN: "localhost"
        PORT: 9012
        STORAGE_PATH: /tmp/test-data3
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
        ENCRYPTION_SECRET: "12345678901234567890123456789012"
        ENCRYPTION_SECRET_IV: "1234123412341234"
    - name: Test administrator UI (encryption)
      run: |
        npm test -- --fgrep "www/administrator" || exit 1
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9013"
        DOMAIN: "localhost"
        PORT: 9013
        STORAGE_PATH: /tmp/test-data4
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
        ENCRYPTION_SECRET: "12345678901234567890123456789012"
        ENCRYPTION_SECRET_IV: "1234123412341234"
