name: npm-publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y redis-server
        npm install mocha puppeteer@2.1.1 @userdashboard/storage-redis --no-save
        git config --global user.name "${{ secrets.NAME }}"
        git config --global user.email "${{ secrets.EMAIL }}"
    - name: Test (fs)
      run: |
        npm test
        npm version patch
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9004"
        DOMAIN: "localhost"
        STORAGE_ENGINE: "@userdashboard/storage-redis"
        REDIS_URL: "redis://localhost:6379"
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
    - uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: Apply automatic changes
        branch: ${{ github.head_ref }}
        commit_options: '--no-verify --signoff'
        repository: .